# Generated by Django 2.1.3 on 2018-12-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='shop',
        ),
    ]
