# Generated by Django 2.1.3 on 2018-12-18 22:37

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goods_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to=goods.models.get_image_name, verbose_name='封面图'),
        ),
    ]
