# Generated by Django 2.1.3 on 2019-01-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190115_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='signer_name',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='singer_mobile',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信支付'), (3, '货到付款'), (4, '银联支付')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserAddress', verbose_name='收获地址'),
        ),
    ]
