# Generated by Django 2.1.3 on 2019-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190125_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='signer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='signer_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='收件手机号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='收货地址'),
        ),
    ]
