# Generated by Django 2.1.3 on 2018-12-18 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '店铺城市',
                'verbose_name_plural': '店铺城市',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='店铺名称')),
                ('desc', models.TextField(default='', verbose_name='店铺描述')),
                ('image', models.ImageField(max_length=50, upload_to='shop/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=50, verbose_name='店铺地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '店铺信息',
                'verbose_name_plural': '店铺信息',
            },
        ),
    ]
