# Generated by Django 2.1.3 on 2018-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifycode',
            name='is_used',
            field=models.IntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
