# Generated by Django 2.1.3 on 2018-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifycode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
