# Generated by Django 2.1.3 on 2019-01-15 17:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181212_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to=users.models.get_image_name, verbose_name='头像'),
        ),
    ]
